# Generated by Django 3.1.5 on 2021-01-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADUrl',
            new_name='SKYUrl',
        ),
    ]
