# Generated by Django 3.1.5 on 2021-01-31 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210131_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='skyurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skyurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skyurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skyurl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
