# Generated by Django 3.1.5 on 2021-01-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20210131_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skyurl',
            options={'verbose_name': 'SKYUrl', 'verbose_name_plural': 'SKYUrls'},
        ),
    ]
